insert into student(id, name, birthdate, address, gender) values (1, 'Merve Anık', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (2, 'Leyna Ak', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (3, 'Anıl Sürel', '1998-08-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (4, 'Cem Güzel', '1998-08-17', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (5, 'Canan Sura', '1997-02-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (6, 'Cemal Aslan', '1997-08-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (7, 'Kardelen Ok', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (8, 'Ahmet Ayan', '1998-08-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (9, 'Cemil Meriç', '1998-08-17', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (10, 'Ali Yücel', '1997-02-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (11, 'Merve Anık', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (12, 'Leyna Ak', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (13, 'Anıl Sürel', '1998-08-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (14, 'Cem Güzel', '1998-08-17', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (15, 'Canan Sura', '1997-02-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (16, 'Ayşe Aslan', '1997-08-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (17, 'Beyza Ok', '1997-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (18, 'Gülşah Ayan', '1998-08-07', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (19, 'Ajda Pekkan', '1998-08-17', 'Merter', 'Female');
insert into student(id, name, birthdate, address, gender) values (20, 'Durul Gül', '1997-02-07', 'Merter', 'Male');
insert into student(id, name, birthdate, address, gender) values (21, 'Kübra Felek', '1997-01-01', 'Güngören', 'Female');

insert into course(id, course_name, course_code, credit_score) values (1, 'Introduction To Java', 111, 4);
insert into course(id, course_name, course_code, credit_score) values (2, 'Object Oriented Programming', 112, 3);
insert into course(id, course_name, course_code, credit_score) values (3, 'Data Structures', 202, 4);
insert into course(id, course_name, course_code, credit_score) values (4, 'Database Systems', 222, 4);
insert into course(id, course_name, course_code, credit_score) values (5, 'Algorithm Analysis', 312, 3);
insert into course(id, course_name, course_code, credit_score) values (6, 'Operations System', 334, 3);

insert into instructor(id, name, address, phone_number) values (1, 'Emine Ekin', 'Şile', '0212-423-6776');
insert into instructor(id, name, address, phone_number) values (2, 'Olcay Yıldız', 'Şile', '0212-423-6476');
insert into instructor(id, name, address, phone_number) values (3, 'Boray Tek', 'Şile', '0212-423-6276');
